# Generated by Django 4.1.5 on 2023-01-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_logged', models.DateField(blank=True)),
                ('foods_consumed', models.ManyToManyField(related_name='user_days', to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
