# Generated by Django 4.1.5 on 2023-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_color'),
        ('user_days', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userday',
            name='foods_consumed',
        ),
        migrations.AddField(
            model_name='userday',
            name='foods_consumed',
            field=models.ManyToManyField(related_name='user_days', to='foods.food'),
        ),
    ]
